services:
  db:
    image: postgres:15
    container_name: friend-gifting-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: friendgifting2024
      POSTGRES_DB: friend_gifting
    ports:
      - "5433:5432"  # Map to 5433 externally to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
